### ISSUE TITLE
Old email and password should be removed from docker-compose-file

### ISSUE THREAD

**Issue by Hugsim** [cthit/Gamma#231]
Hi guys, dHack here. We did a routine scan of related repositories and found a vulnerable non-monad email and password in your functor-related docker-compose.yml-file. Your costates also seem to be unaligned.

Jokes aside, you have an email and password in /docker-compose.yml that maybe shouldn't be there.

**Comment by Portals** [comment]
It's fineeeeee, it's an old password 😂
