### ISSUE TITLE
Be able to create dynamic super group types

### ISSUE THREAD

**Issue by Gurrit** [cthit/Gamma#301]
This would prevent the issue with mass bcc mailing, which google doens't like.

**Comment by Portals** [comment]
Maybe create a group without super group, and add the functionality to make it hidden. So that a mail group can be created wihtout anyone seeing it (except admins ofc)

**Comment by Portals** [comment]
This would mean however that we needed another group type or make it dynamic #147

**Comment by Portals** [comment]
My idea is to move from the GroupType enum. Along with this feature and with #786, you can create mailing lists

**Comment by Portals** [comment]
I think that adding settings to goldapps so that not everyone can send them to these groups is better than making them hidden.
