### ISSUE TITLE
Use Instant (or possibly Datetime) instead of Calendar

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/Gamma#493]

**Comment by Portals** [comment]
@Gurr1 This should be done for the v1.0 if anything right?

**Comment by Portals** [comment]
Not that the frontend needs to be fixed if this is the case: 

https://stackoverflow.com/questions/48310483/java-javascript-java-time-instant-serialization-to-javascript-date

**Comment by Portals** [comment]
Closing since `becomesActive` and `becomesInactive` was removed from groups
