### ISSUE TITLE
reformat JSON files sent from the backend

### ISSUE THREAD

**Issue by Gurrit** [cthit/Gamma#506]
currently, lists are sent without a identifer, which does not follow specfications

**Comment by Portals** [comment]
Is this really necessary? I think it's fine as it is. It helps imo to keep complexity down if we ignore this

**Comment by Portals** [comment]
One option would be to implement [HATEOS](https://en.wikipedia.org/wiki/HATEOAS) using [Spring HATEOS project](https://spring.io/projects/spring-hateoas). But this isn't IMO needed to the smaller scale that we're working on. Especially since the APIs now are much smaller and more specialized.
