### ISSUE TITLE
The matrix-background on the login-screen borks my pw-manager

### ISSUE THREAD

**Issue by hulthe** [cthit/Gamma#558]
![bild](https://user-images.githubusercontent.com/6770850/74931528-10ed7a80-53e0-11ea-907c-365b86386e24.png)
助けてください

**Comment by Portals** [comment]
This will not be prioritized due to lack of time. If anyone can find why, then please comment and then we can look into how long it will take to actually fix. As of right now the canvas rendering will stays because of A E S T H E T I C S.
