### ISSUE TITLE
Refactor security for Gamma

### ISSUE THREAD

**Issue by Portals** [cthit/Gamma#614]
- [x] Migrate from Spring Security OAuth 2.x to Spring Security 5.2.x
- [x] Frontend should use a cookie for authentication, not oauth2 flow.
- [x] API keys should only work on their specific type. Add user tests in case URLs change so that an admin user can't access APIs by mistake
- [x] Add API keys that are connected to clients so that clients can't access users that have not accepted the user agreement for the client. These API keys should only have read access. 
- [x] JWT access token should only be used to have read access for /api/v1/users/me.
- [x] If a user hasn't accepted the latest user agreement, then the user must no be able to use the API in any way other than accepting the user agreement or deleting their account.
- [x] Admins, or members of a given group, should only be able to upload avatars and banners.
- [x] Admins should be able to remove any users avatar.

**Comment by Dr-Horv** [comment]
I'm not sure I understand, why a middle ware?

**Comment by Portals** [comment]
Right now the authorization code is used straight in the frontend without any further security. To easily fix this issue we suggest having a middleware, a nodejs server, that keeps a login session and forwards requests from the frontned to backend.

**Comment by Dr-Horv** [comment]
> Right now the authorization code is used straight in the frontend 
What does this mean? 

You use JWT right? Then I would assume that backend creates the JWT including signature created by some backend-only-known secret together with the data in the token and then gives it out to the frontend. Calls to the backend from the frontend thereafter uses the provided signature to see if it matches with the content, it's all good. No?

**Comment by Portals** [comment]
@Gurr1 Since frontend now is going to use a cookie, should the JWT token only have read access for /users/me?

**Comment by Gurr1** [comment]
Of the top of my mind, I can't think of a instance where JWT token should require write access
