### ISSUE TITLE
Crash possibly caused by setting a gif as my avatar image

### ISSUE THREAD

**Issue by Deltaphish** [cthit/Gamma#615]
While trying to add a client to gamma, I looked around the settings and saw I could change my avatar picture.

Just wanting to test it I uploaded the first picture I had on my desktop:
https://drive.google.com/file/d/1JbUq3Jl9Kehx6CoxiavKpOxUk9pCOCcy/view?usp=sharing

In hindsight I probably should have not tried to upload a 21MB gif as a profile picture, but this is something gamma should probably warn/block from happening.

After selecting the gif with my file-explorer (Windows), I pressed upload image. This gave no response. I tried a few more times but nothing happend. I assumed that it had worked and continued with my buisness.

Couple seconds later Gamma started givning 504 errors and blank screens with blue headers with just the text "gamma".

Uploading a large gif as an avatar may or may not have caused the crash, but having restrictions on what format/size the avatar pictures are uploaded should probably be implemented.

**Comment by Portals** [comment]
Closing since ImageIT is no longer used.
