### ISSUE TITLE
GDPR table constantly changing size.

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#622]
The table on the GDPR page (gamma.chalmers.it/gdpr) changes size whenever one goes to the next page. A better solution (IMO), to avoid buttons moving around constantly, would be to have it at a fixed size, covering most of the width of the page (most of which is currently unused. See image below, green is what the current table covers (ish as it changes depending on the content), the red is approximately what I would like it to be (static, independent of the content).

<img width="1500" alt="gamma_issue" src="https://user-images.githubusercontent.com/16452604/79347439-fcd37e80-7f33-11ea-966d-60573bb08ed5.png">

**Comment by Portals** [comment]
Will be resolved by #619 since that PR upgrades rdc to v1.0

**Comment by ViddeM** [comment]
Great!

**Comment by Portals** [comment]
This won't be fixed by #606, so the issue stands
