### ISSUE TITLE
User agreement should be editable by admins

### ISSUE THREAD

**Issue by Sponken** [cthit/Gamma#702]

**Comment by Portals** [comment]
Why should user agreement be editable by admins?

**Comment by Sponken** [comment]
It's far from a necessity , but it would have been usefull when this issue was created. There could be cases where the user agreement needs to be updated, and it would seem useful for admins to be able to do this in the frontend

**Comment by Portals** [comment]
I think we're talking about different things. My comment was about changing if a user has accepted the user agreement. But now it's obvious that it's not what you mean. Sorry bout that

**Comment by Portals** [comment]
I think instead we will keep the arrangement with having the user agreement on Github. And instead, rely on #703 to reset for every user.
