### ISSUE TITLE
Add ENV variable for frontend development proxy in package.json

### ISSUE THREAD

**Issue by Portals** [cthit/Gamma#709]
It's useful when creating a docker network

**Comment by molleer** [comment]
Witing on this one to merge with prod...
https://github.com/facebook/create-react-app/pull/8598

**Comment by Portals** [comment]
While a good find, I solved it via `setupProxy.js`! It's already merged

**Comment by unclechu** [comment]
@Portals `setupProxy.js` works a bit differently, it doesn't fully replace original `proxy` solution.

@molleer If you would like to see https://github.com/facebook/create-react-app/pull/8598 being merged please show your user's interest in it (e.g. by leaving a comment or with a thumbs up emoji-reaction). I believe (or maybe I just want to believe) it would increase chances of this MR at least being reviewed properly, currently no one is even paying attention to it.
