### ISSUE TITLE
Make use of width on register user screen.

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#711]
![image](https://user-images.githubusercontent.com/16452604/81319271-b7682400-908f-11ea-9ae5-f507c532b5d4.png)
The Register user screen uses a lot of vertical space but not that much horizontal space (see image above for reference). I would personally prefer to use more of that horizontal space by, for example, using a two-column layout.

**Comment by ViddeM** [comment]
It would be nice to continue using the current layout on for example phones (i.e. when screen size is below xx width).

**Comment by Portals** [comment]
Are you looking for something like this? 
![image](https://user-images.githubusercontent.com/7045380/81340222-c52da180-90af-11ea-8cb8-dac2212b7023.png)

**Comment by Portals** [comment]
I like the way it's linear right now. It's imo easier on the eyes to just go straight down instead of zig-zag:ing.
