### ISSUE TITLE
Adding a new user to a group and not selecting a post for that user, breaks gamma frontend

### ISSUE THREAD

**Issue by molleer** [cthit/Gamma#715]
You should not be able of going to the final step in the wizard unless you have selected a post for each member.

**Comment by Portals** [comment]
There's an issue with the yup validation schema / `DigitEditDataCard` (innerForm)

**Comment by Portals** [comment]
Actually, me who didn't think of actually setting the `disabled` prop. Will be fixed in an upcoming PR.
