### ISSUE TITLE
Add ability to search for more than one thing when searching for users.

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#722]
At the moment one appears only to be able to search for one attribute at the time when searching for users in gamma (at least on the /users screen). It would be great to be able to search for (for example) 
* firstname lastname
* firstname year
* nick firstname

**Comment by Portals** [comment]
Duplicate of #717

**Comment by ViddeM** [comment]
MB, I'm blind. 👍

**Comment by Portals** [comment]
No problems, I renamed that issue to be more general than what I had earlier. So I sort of merged the two issues.
