### ISSUE TITLE
Aborting log in to client application and then trying to log in to Gamma will redirect the user to the client

### ISSUE THREAD

**Issue by molleer** [cthit/Gamma#749]
Replicate bug

1. Go to suggestit.chalmers.it
2. Press login, (you should be presented with the login screen, if not then logout from gamma and start over)
3. Do not log in, open another window and go to gamma.chalmers.it
4. Login to gamma

When you log in to gamma you will be redirected to suggestit.chalmers.it

**Comment by Portals** [comment]
I'm closing this since we should instead rely on #575 for login and logout in the future. 
I'm going to remove the code that's causing this issue.
