### ISSUE TITLE
Be able to restrict who can authorize with a client

### ISSUE THREAD

**Issue by rosengrenen** [cthit/Gamma#787]
As it stands now, everyone can authorize with a client, and there is no way to restrict that. Some clients would need that possibility, such as committee wikis and other services (such as rancher/portainer) where only members of that group should have access, but the services' generic oauth2 modules don't support gammas or any other form of access control.

It would be great if clients could be restricted on the following (and any/some combinations of them):
* User is part of group of super group (e.g. any digit or any didit)
* User is part of active group of super group (e.g. current digit -> digit20)

**Comment by Portals** [comment]
Im going to implement it by being able to restrict a client to one or more authority level
