### ISSUE TITLE
500 error when trying to auth with invalid client

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#871]
I tried to auth with a client that doesn't exist anymore and got a 500 error for my trouble.

This should lead to a non 5XX error since it is clearly a client fault.

This can be reproduced by going to the `oauth2/authorize` endpoint and provide invalid details e.g.: `https://auth.chalmers.it/oauth2/authorize?response_type=code&client_id=asd&redirect_uri=peppe&scope=openid%20profile&state=1111`

**Comment by Portals** [comment]
This also happens if illegal argument exception.
