### ISSUE TITLE
Feedback on invalid images for banners and avatars is not shown

### ISSUE THREAD

**Issue by simon-wg** [cthit/Gamma#873]
When attempting to add a banner to a group it replaces the <article> containing the banner element with the "My Profile" page.

![Screenshot 2024-06-19 164608](https://github.com/cthit/Gamma/assets/18512096/604bee28-fae5-4534-9f22-b883ce5ca96b)

![Screenshot 2024-06-19 164615](https://github.com/cthit/Gamma/assets/18512096/980d511d-36a9-4f68-99aa-7708c441d1d6)

**Comment by GAsplund** [comment]
I think that this is due to the site throwing an unhandled exception when you upload an image that has an invalid extension (anything not .jpg, .png or .webp or not lower-case) or a size >2MB

**Comment by simon-wg** [comment]
that makes sense considering the image I'm trying to upload is 11 Mb, I'll try to compress it more

**Comment by simon-wg** [comment]
can confirm that it works with a compressed jpg

**Comment by Portals** [comment]
Yes, feedback has gone missing. Will update title.

**Comment by Portals** [comment]
There is something weird when I have `servlet.multipart.max-file-size=2MB`, along with CSRF. The CSRF just gets ignored... I "solved" this by increasing the max-file-size, and moving the validation of max file size into `LocalImageService`.
