### ISSUE TITLE
500 error when requesting supergroups

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#879]
When calling the `https://auth.chalmers.it/api/client/v1/superGroups` endpoint I get a 500 error.
Other endpoints work fine so auth and so on seem to be working.
I'm not quite sure what is causing this and the logs are soo filled with stacktraces that it is difficult to figure our which one belongs to this error. 

Potentially it is this exception (but not sure):
```
 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "#authentication.getDetails().gammaUser().nick().value()" (template: "common/header" - line 72, col 18)] with root cause

org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method gammaUser() on null context object
```

Sidenote, perhaps it would be useful to log a bit more than just stack traces, e.g. when receiving a request or similar because currently (at least I find it so) it seems quite difficult to debug specific errors for this service.

**Comment by Portals** [comment]
Issue was that I had not approved the client api to use SuperGroupFacade.getAll() 👍
