### ISSUE TITLE
500 Error on trying to retrieve user that hasn't accepted client

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#894]
I'm not 100% sure this is the issue but I get a 500 error when trying to use a client key to retrieve a user that has not accepted the client.

This should preferably lead to a 4XX error with a message saying why it failed. 
Or a 404 "Not found" if one wants to hide that the user exists, although I think this seem unnecessary since the user ID is a UUID and if they have the UUID they probably know that the user exists so I'd argue for the more approach in this case.

**Comment by Portals** [comment]
Yes, this is a bug! There is a a exception that get's thrown due to access denied that is not caught properly. Will resolve 👍
