### ISSUE TITLE
Query for users by cid as well as user_id

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#895]
Currently there is an endpoint for retrieving a user by user ID but not by cid.

This feature existed in the 'current' version of gamma and as cid is often used as an ID at the IT division it would be good if the endpoint allowed either a user ID or a cid. Alternatively these could be two different endpoints.

**Comment by Portals** [comment]
@Oscariremma What is your opinion on this? I guess it has to do with for example being able to run `hubbit.chalmers.it/{cid}` in an easy way.

**Comment by Oscariremma** [comment]
Is it possible for a user to change their CID in Gamma? I am also guessing that you have a unique constraint on the CID in the database? 

If it is "impossible" to change a CID and they are unique in the database it could be fine to allow this but it should probably be discouraged as CID:s contains some personal information in the form of name which is preferable that only Gamma stores from a GDPR point of view.

Do you remember what the usage of this would be @ViddeM ?

**Comment by Portals** [comment]
@Oscariremma It is not possible to change your cid in Gamma. It is also possible, in theory, that a CID is reused in the future for Chalmers. (which I do not want to think about right now 😆) It is also enforced to be unique, but that can come to change. 

I think it would be most wise to close this issue unfortunately, and continue to encourage using user id.
