### ISSUE TITLE
Add shared clients

### ISSUE THREAD

**Issue by simon-wg** [cthit/Gamma#905]
As it is right now clients are owned by individual users.

Personally I think it might be a nice feature to enable something like shared clients within a super group.

For example if I want to create a client for the digit-wiki, I would be able to select digIT in a dropdown menu in order to share the client with all members of that super group.

**Comment by GAsplund** [comment]
I think what you're looking for might be official clients that have restrictions put on them? Those aren't owned by anyone, and they allow you to restrict who, on an individual user or group level, may authenticate through it.

**Comment by simon-wg** [comment]
Yes that would work, is it a feature of Gamma right now or is it a suggestion you're making?

**Comment by simon-wg** [comment]
What I'm thinking of is allowing an entire super group to manage restrictions etc. for a client.

**Comment by GAsplund** [comment]
> Yes that would work, is it a feature of Gamma right now or is it a suggestion you're making?

That exists as described today.

> What I'm thinking of is allowing an entire super group to manage restrictions etc. for a client.

This does not exist, but is there any specific case this would be useful?

**Comment by simon-wg** [comment]
I am thinking it might be useful for example for digit, where wither one person will have a bunch of clients for every committé's wiki pages and all official IT-systems, or they will be spread out among members. 

That way all members would be able to update authorities for clients.

Say for example I create a client for the digIT-wiki, and misconfigure something. Om that case any other member of a selected super group would be able to adjust it without needing to create their own client and changing the client in portainer.

**Comment by simon-wg** [comment]
However official clients might fill that purpose depending on who can view/edit them.

How would one go about using official clients in that case?

**Comment by Oscariremma** [comment]
Official clients can be created/managed by any admin user in Gamma
