### ISSUE TITLE
Removing a user from a group fails

### ISSUE THREAD

**Issue by Oscariremma** [cthit/Gamma#926]
Sometimes (?) removing a user from a group causes an error (which results in a 405 #925).
This is caused by the unofficialPostName entry remaining in the form POST request while the post and user id is removed.
If we manually send a request with this removed it works.

![image](https://github.com/user-attachments/assets/1ec166f0-b3b1-49a7-a488-9ded36dc286c)

**Comment by Portals** [comment]
Yeah, found that out the other day. Closing this once due to duplication. 

#922
